name: linux-ci

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  BUILD_TYPE: Release

jobs:
  cmake-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update container
      run:
        sudo apt-get update &&
        sudo apt-get install -y build-essential gcc g++ &&
        python -m pip install --upgrade pip

    - name: Install Kokkos
      run:
        python -m pip install 'cmake==3.18.4' &&
        git clone https://github.com/kokkos/kokkos.git /tmp/kokkos-source &&
        cmake -B /tmp/kokkos-build
          -DKokkos_ENABLE_SERIAL=ON
          -DKokkos_ENABLE_OPENMP=ON
          -DBUILD_SHARED_LIBS=ON
          /tmp/kokkos-source &&
        cmake --build /tmp/kokkos-build --target all --parallel 2 &&
        sudo cmake --build /tmp/kokkos-build --target install --parallel 2

    - name: Configure CMake
      run:
        python -m pip install -r requirements.txt &&
        cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DENABLE_LAYOUTS=OFF
          -DENABLE_EXAMPLES=ON
          -DENABLE_WERROR=ON
          -DPython3_EXECUTABLE=$(which python)

    - name: Build
      run:
        cmake --build ${{github.workspace}}/build --target all --parallel 2 &&
        sudo cmake --build ${{github.workspace}}/build --target install --parallel 2

    - name: Import Test
      working-directory: ${{github.workspace}}/build
      run:
        mkdir scratch &&
        cd scratch &&
        export PYTHONPATH=/usr/local/lib/python${{ matrix.python-version }}/site-packages:${PYTHONPATH} &&
        python -c "import kokkos; print(kokkos.__file__)"

    - name: Test
      working-directory: ${{github.workspace}}/build
      run:
        export PYTHONPATH=${PWD}:/usr/local/lib/python${{ matrix.python-version }}/site-packages:${PYTHONPATH} &&
        ls &&
        python ./ex-numpy.py

  python-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update container
      run:
        sudo apt-get update &&
        sudo apt-get install -y build-essential gcc g++ &&
        python -m pip install --upgrade pip

    - name: Install Kokkos
      run:
        python -m pip install 'cmake==3.18.4' &&
        git clone https://github.com/kokkos/kokkos.git /tmp/kokkos-source &&
        cmake -B /tmp/kokkos-build
          -DKokkos_ENABLE_SERIAL=ON
          -DKokkos_ENABLE_OPENMP=ON
          -DCMAKE_CXX_STANDARD=17
          -DBUILD_SHARED_LIBS=ON
          /tmp/kokkos-source &&
        cmake --build /tmp/kokkos-build --target all --parallel 2 &&
        sudo cmake --build /tmp/kokkos-build --target install --parallel 2

    - name: Build
      run:
        python -m pip install -r requirements.txt &&
        python setup.py install
          --enable-layouts
          --disable-memory-traits
          --enable-werror
          -- -DENABLE_EXAMPLES=ON

    - name: Import Test
      run:
        mkdir scratch &&
        cd scratch &&
        python -c "import kokkos; print(kokkos.__file__)"

    - name: Test
      working-directory: ${{github.workspace}}/_skbuild
      run:
        cd ./*/cmake-build &&
        ls &&
        python ./ex-numpy.py

  pip-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update container
      run:
        sudo apt-get update &&
        sudo apt-get install -y build-essential gcc g++ &&
        python -m pip install --upgrade pip

    - name: Install Kokkos
      run:
        python -m pip install 'cmake==3.18.4' &&
        git clone https://github.com/kokkos/kokkos.git /tmp/kokkos-source &&
        cmake -B /tmp/kokkos-build
          -DKokkos_ENABLE_SERIAL=ON
          -DKokkos_ENABLE_PTHREAD=ON
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          /tmp/kokkos-source &&
        cmake --build /tmp/kokkos-build --target all --parallel 2 &&
        sudo cmake --build /tmp/kokkos-build --target install --parallel 2

    - name: Build
      # Build your program with the given configuration
      run:
        python -m pip install -r requirements.txt &&
        PYKOKKOS_BASE_SETUP_ARGS="-DENABLE_WERROR=ON" python -m
          pip install -v --user --no-deps -e build
          --install-option=--disable-memory-traits
          --install-option=--cxx-standard=17

    - name: Import Test
      run:
        mkdir scratch &&
        cd scratch &&
        python -c "import kokkos; print(kokkos.__file__)"
